name: building, testing, linting 🍏
run-name: ${{ github.actor }} is testing out
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build production project
        if: always()
        run: npm run build:prod

      - name: Run linting typescript
        if: always()
        run: npm run lint:ts

      - name: Run linting scss
        if: always()
        run: npm run lint:scss

      - name: Run unit testing
        if: always()
        run: npm run test:unit

      # - name: Build storybook
      #   if: always()
      #   run: npm run storybook:build

      # - name: Run screenshot testing
      #   if: always()
      #   run: npm run test:ui:ci

